### ISSUE TITLE
removing devDependencies

### ISSUE THREAD

**Issue by matthewchung74** [willyg302/gulp-awslambda#2]
Hello willyg302, 

Do you have a gulpfile using using gulp-awslamda which only copies the production node modules to aws? I'm trying to remove the devDependencies from being copied but am stuck on integrating gulp-install. Anyways, any help is appreciated.

**Comment by willyg302** [comment]
I tried using gulp-install but quickly gave up because it seems to install the Node modules in place and doesn't forward them down the stream, which means they won't be included in the zip. My solution was the following:

Assume a package structure like this:

```
src/
    index.js
    package.json
Gulpfile.js
package.json
publish.sh
```

The `src/` directory contains your actual Lambda function package, including any dependencies needed (async, Mocha, etc.). Then there's the "outer" directory which contains the build logic. I whipped up a quick shell script -- `publish.sh` -- to do what I thought gulp-install _would_ do:

``` bash
rm -rf dest
cp -R src dest
cd dest && npm install --production && cd ..
gulp
```

And then in the Gulpfile:

``` js
gulp.task('default', function() {
    return gulp.src('dest/**/*')
        .pipe(zip('archive.zip'))
        .pipe(lambda(lambda_params, opts))
        .pipe(gulp.dest('.'));
});
```

Not entirely pretty, but it works. Let me know if that helps!

**Comment by matthewchung74** [comment]
Thanks for responding Willy. In this case, if Mocha is in src/ , wouldn't
that get copied up to AWS as well?

On Thu, Jul 30, 2015 at 9:48 PM, WillyG Productions <
notifications@github.com> wrote:

> I tried using gulp-install but quickly gave up because it seems to install
> the Node modules in place and doesn't forward them down the stream, which
> means they won't be included in the zip. My solution was the following:
> 
> Assume a package structure like this:
> 
> src/
>     index.js
>     package.json
> Gulpfile.js
> package.json
> publish.sh
> 
> The src/ directory contains your actual Lambda function package,
> including any dependencies needed (async, Mocha, etc.). Then there's the
> "outer" directory which contains the build logic. I whipped up a quick
> shell script -- publish.sh -- to do what I thought gulp-install _would_
> do:
> 
> rm -rf dest
> cp -R src destcd dest && npm install --production && cd ..
> gulp
> 
> And then in the Gulpfile:
> 
> gulp.task('default', function() {
>     return gulp.src('dest/*_/_')
>         .pipe(zip('archive.zip'))
>         .pipe(lambda(lambda_params, opts))
>         .pipe(gulp.dest('.'));
> });
> 
> Not entirely pretty, but it works. Let me know if that helps!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/willyg302/gulp-awslambda/issues/2#issuecomment-126566431
> .

## 

Regards,
Matt

**Comment by willyg302** [comment]
Oh you're right, sorry about that. The goal is to copy over to `dest` but exclude `node_modules`, which means that this command (instead of `cp`) should do the trick:

```
rsync -r src dest --exclude node_modules
```

**Comment by matthewchung74** [comment]
Thank you.

On Friday, July 31, 2015, WillyG Productions notifications@github.com
wrote:

> Oh you're right, sorry about that. The goal is to copy over to dest but
> exclude node_modules, which means that this command (instead of cp)
> should do the trick:
> 
> rsync -r src dest --exclude node_modules
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/willyg302/gulp-awslambda/issues/2#issuecomment-126854533
> .

## 

Regards,
Matt
