### ISSUE TITLE
Add support for publishing versions

### ISSUE THREAD

**Issue by deepakjois** [willyg302/gulp-awslambda#4]
AWS Lambda recently launched support for versions: http://docs.aws.amazon.com/lambda/latest/dg/versioning-aliases.html

There is a corresponding update to the Javscript SDK, where both the `updateFunctionCode` and `createFunction`, now take a `Publish` property in the params object which can be set to `true` or `false`:
- http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#createFunction-property
- http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#updateFunctionCode-property

Please add support for it in your plugin.

**Comment by willyg302** [comment]
Added support in 0.2.3, just provide the `Publish` property as part of `lambda_params`. Let me know if you run into any issues. Thanks!
